/*----------------------------------------------------------
MASV: 4301104032	
HO TEN: VO THE DUY
LAB: 04
NGAY:
----------------------------------------------------------*/

USE [master]
GO

IF(DB_ID(N'QuanLySinhVienDonGian') IS NOT NULL)
BEGIN
	DROP DATABASE [QuanLySinhVienDonGian]
END
GO 

CREATE DATABASE [QuanLySinhVienDonGian]
GO 

USE [QuanLySinhVienDonGian]
GO 		


CREATE TABLE [NHANVIEN]
(
	[MANV] VARCHAR(20) PRIMARY KEY,
	[HOTEN] NVARCHAR(100) NOT NULL,
	[EMAIL] VARCHAR(20) NULL,
	[LUONG] VARBINARY(8000) NULL,
	[TENDN] NVARCHAR(100) NOT NULL,
	[MATKHAU] VARBINARY(8000) NOT NULL
)
GO 

CREATE TABLE [LOP]
(
	[MALOP] VARCHAR(20) PRIMARY KEY,
	[TENLOP] NVARCHAR(100) NOT NULL,
	[MANV] VARCHAR(20) NULL
)
GO 

CREATE TABLE [SINHVIEN]
(
	[MSSV] NVARCHAR(20) PRIMARY KEY,
	[HOTEN] NVARCHAR(100) NOT NULL,
	[NGAYSINH] DATETIME NULL,
	[DIACHI] NVARCHAR(200) NULL,
	[MALOP] VARCHAR(20) NULL,
	[TENDN] NVARCHAR(20) NOT NULL,
	[MATKHAU] VARBINARY(8000) NOT NULL
)
GO 

--ALTER TABLE dbo.[LOP] ADD CONSTRAINT fk_LOP_NHANVIEN FOREIGN KEY ([MANV]) REFERENCES dbo.[NHANVIEN]([MANV])
--ALTER TABLE dbo.[SINHVIEN] ADD CONSTRAINT fk_SINHVIEN_LOP FOREIGN KEY ([MALOP]) REFERENCES dbo.[LOP]([MALOP])
--GO 


CREATE PROCEDURE [SP_INS_ENCRYPT_SINHVIEN]
	@MASV NVARCHAR(20),
	@HOTEN NVARCHAR(100),
	@NGAYSINH DATETIME,
	@DIACHI NVARCHAR(200),
	@MALOP VARCHAR(20),
	@TENDN NVARCHAR(20),
	@MATKHAU VARCHAR(MAX)
AS
BEGIN
	INSERT dbo.SINHVIEN (MSSV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, MATKHAU)
	VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, CONVERT(VARBINARY(8000), @MATKHAU))
END
GO 

EXEC dbo.SP_INS_ENCRYPT_SINHVIEN @MASV = N'SV01',
                                 @HOTEN = N'NGUYEN VAN A',
                                 @NGAYSINH = '1/1/1990',
                                 @DIACHI = N'280 AN DUONG VUONG',
                                 @MALOP = 'CNTT-K35',
                                 @TENDN = N'NVA',
                                 @MATKHAU = '545045840580458058045804580458435'
GO

CREATE SYMMETRIC KEY [SK_4301104032]
WITH 
	ALGORITHM = AES_256,
	KEY_SOURCE = '4301104032'
ENCRYPTION BY PASSWORD = 'K4301104032'
GO 

CREATE PROCEDURE [SP_INS_ENCRYPT_NHANVIEN]
	@MANV NVARCHAR(20),
	@HOTEN NVARCHAR(100),
	@EMAIL VARCHAR(20),
	@LUONG VARCHAR(MAX),
	@TENDN NVARCHAR(100),
	@MATKHAU VARCHAR(MAX)
AS
BEGIN
	OPEN SYMMETRIC KEY [SK_4301104032] DECRYPTION BY PASSWORD = 'K4301104032' 

	DECLARE @MATKHAU_ENCRYPTED VARBINARY(8000)
	DECLARE @LUONG_ENCRYPTED VARBINARY(8000)

	SET @MATKHAU_ENCRYPTED = CONVERT(VARBINARY(8000), HASHBYTES('SHA1', @MATKHAU))
	SET @LUONG_ENCRYPTED = CONVERT(VARBINARY(8000), ENCRYPTBYKEY(KEY_GUID('SK_4301104032'), @LUONG))

	INSERT dbo.NHANVIEN (MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU)
	VALUES (@MANV, @HOTEN, @EMAIL, @LUONG_ENCRYPTED, @TENDN, @MATKHAU_ENCRYPTED)

	CLOSE SYMMETRIC KEY [SK_4301104032]
END
GO 

EXEC dbo.SP_INS_ENCRYPT_NHANVIEN @MANV = N'NV01',
                                 @HOTEN = N'NGUYEN VAN A',
                                 @EMAIL = 'NVA@',
                                 @LUONG = 'aaaaaaaa',
                                 @TENDN = N'NVA',
                                 @MATKHAU = 'bbbbbbbb'
GO 

CREATE PROCEDURE [SP_SEL_ENCRYPT_NHANVIEN]
AS
BEGIN
	OPEN SYMMETRIC KEY [SK_4301104032] DECRYPTION BY PASSWORD = 'K4301104032'
	
	SELECT MANV, HOTEN, EMAIL, CONVERT(VARCHAR(MAX), DECRYPTBYKEY([LUONG])) AS [LUONG]
	FROM dbo.NHANVIEN

	CLOSE SYMMETRIC KEY [SK_4301104032]
END
GO

EXEC dbo.SP_SEL_ENCRYPT_NHANVIEN
GO 

ALTER PROCEDURE [SP_SEL_USER]
	@TENDN NVARCHAR(MAX),
	@MD5PWD VARCHAR(MAX),
	@SHA1PWD VARCHAR(MAX)
AS
BEGIN
	DECLARE @ACCEPT_LOGIN INT
	
	IF EXISTS 
	(
		SELECT 
			TENDN, 
			MATKHAU 
		FROM dbo.NHANVIEN 
		WHERE 
			TENDN = @TENDN AND 
			(
				(SELECT CAST('' AS XML).value('xs:hexBinary(sql:column("MATKHAU"))', 'varchar(max)')) = @MD5PWD OR 
				(SELECT CAST('' AS XML).value('xs:hexBinary(sql:column("MATKHAU"))', 'varchar(max)')) = @SHA1PWD
			)
		UNION 
		SELECT 
			TENDN, 
			MATKHAU 
		FROM dbo.SINHVIEN 
		WHERE 
			TENDN = @TENDN AND 
			(
				(SELECT CAST('' AS XML).value('xs:hexBinary(sql:column("MATKHAU"))', 'varchar(max)')) = @MD5PWD OR 
				(SELECT CAST('' AS XML).value('xs:hexBinary(sql:column("MATKHAU"))', 'varchar(max)')) = @SHA1PWD
			)
	)
	BEGIN
		SET @ACCEPT_LOGIN = 1
	END
	ELSE
    BEGIN
		SET @ACCEPT_LOGIN = 0
	END
    
	SELECT @ACCEPT_LOGIN AS [RESULT]
END
GO 

CREATE TABLE [tempNHANVIEN]
(
	[MANV] VARCHAR(20) NULL,
	[HOTEN] NVARCHAR(100) NULL,
	[EMAIL] VARCHAR(20) NULL,
	[LUONG] VARCHAR(MAX) NULL,
	[TENDN] NVARCHAR(100) NULL,
	[MATKHAU] VARCHAR(MAX) NULL
)
GO 