/*----------------------------------------------------------
MASV: 4301104032	
HO TEN: VO THE DUY
LAB: 03_d
NGAY:
----------------------------------------------------------*/

USE [QLSV]
GO


CREATE PROCEDURE [SP_SEL_USER]
	@TENDN NVARCHAR(MAX),
	@MATKHAU VARCHAR(MAX)
AS
BEGIN
	SELECT COUNT(*) AS [COUNT] 
	FROM (
		SELECT [TENDN] FROM dbo.[NHANVIEN] WHERE [TENDN] = @TENDN AND [MATKHAU] = HASHBYTES('SHA1', @MATKHAU)
		UNION 
		SELECT [TENDN] FROM dbo.[SINHVIEN] WHERE [TENDN] = @TENDN AND [MATKHAU] = HASHBYTES('MD5', @MATKHAU)
	) AS [TABLE]
END
GO 

	