/*----------------------------------------------------------
MASV: 4301104032	
HO TEN: VO THE DUY
LAB: 03_b
NGAY:
----------------------------------------------------------*/

USE [QLSV]
GO


CREATE TABLE [NHANVIEN]
(
	[MANV] VARCHAR(20) PRIMARY KEY,
	[HOTEN] NVARCHAR(100) NOT NULL,
	[EMAIL] VARCHAR(20) NULL,
	[LUONG] VARBINARY(8000) NULL,
	[TENDN] NVARCHAR(100) NOT NULL,
	[MATKHAU] VARBINARY(8000) NOT NULL
)
GO 

CREATE TABLE [LOP]
(
	[MALOP] VARCHAR(20) PRIMARY KEY,
	[TENLOP] NVARCHAR(100) NOT NULL,
	[MANV] VARCHAR(20) NULL
)
GO 

CREATE TABLE [SINHVIEN]
(
	[MSSV] NVARCHAR(20) PRIMARY KEY,
	[HOTEN] NVARCHAR(100) NOT NULL,
	[NGAYSINH] DATETIME NULL,
	[DIACHI] NVARCHAR(200) NULL,
	[MALOP] VARCHAR(20) NULL,
	[TENDN] NVARCHAR(20) NOT NULL,
	[MATKHAU] VARBINARY(8000) NOT NULL
)
GO 

--ALTER TABLE dbo.[LOP] ADD CONSTRAINT fk_LOP_NHANVIEN FOREIGN KEY ([MANV]) REFERENCES dbo.[NHANVIEN]([MANV])
--ALTER TABLE dbo.[SINHVIEN] ADD CONSTRAINT fk_SINHVIEN_LOP FOREIGN KEY ([MALOP]) REFERENCES dbo.[LOP]([MALOP])