/*----------------------------------------------------------
MASV: 4301104032	
HO TEN: VO THE DUY
LAB: 03_c
NGAY:
----------------------------------------------------------*/

USE [QLSV]
GO


--i)********************************************************
CREATE PROCEDURE [SP_INS_SINHVIEN]
	@MSSV NVARCHAR(20),
	@HOTEN NVARCHAR(100),
	@NGAYSINH DATETIME,
	@DIACHI NVARCHAR(200),
	@MALOP VARCHAR(20),
	@TENDN NVARCHAR(100),
	@MATKHAU VARCHAR(MAX)
AS 
BEGIN
	DECLARE @MATKHAU_ENCRYPTION VARBINARY(8000)
	SET @MATKHAU_ENCRYPTION = HASHBYTES('MD5', @MATKHAU)
	INSERT dbo.SINHVIEN ([MSSV], [HOTEN], [NGAYSINH], [DIACHI], [MALOP], [TENDN], [MATKHAU])
	VALUES (@MSSV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, @MATKHAU_ENCRYPTION)
END
GO 

EXEC dbo.[SP_INS_SINHVIEN]	@MSSV = N'SV01',
							@HOTEN = N'Nguyen Van A',
							@NGAYSINH = '1990-1-1',
							@DIACHI = N'280 AN DUONG VUONG',
							@MALOP = 'CNTT-K35',
							@TENDN = N'NVA',
							@MATKHAU = '123456'
GO

--ii)*******************************************************
--DROP SYMMETRIC KEY [SK_4301104032]
--GO 

CREATE SYMMETRIC KEY [SK_4301104032]
WITH  
    ALGORITHM = AES_256,  
	KEY_SOURCE = '4301104032'
ENCRYPTION BY PASSWORD = 'K4301104032'; 
GO 

CREATE PROCEDURE [SP_INS_NHANVIEN ]
    @MANV VARCHAR(20),
	@HOTEN NVARCHAR(100),
	@EMAIL VARCHAR(20),
	@LUONG VARCHAR(MAX),
	@TENDN NVARCHAR(100),
	@MATKHAU VARCHAR(MAX)
AS  
BEGIN  
    OPEN SYMMETRIC KEY [SK_4301104032] DECRYPTION BY PASSWORD = 'K4301104032'  

	DECLARE @MATKHAU_ENCRYPTION VARBINARY(8000)
	DECLARE @LUONG_ENCRYPTION VARBINARY(8000)
	SET @MATKHAU_ENCRYPTION = HASHBYTES('SHA1', @MATKHAU)
	SET @LUONG_ENCRYPTION = ENCRYPTBYKEY(KEY_GUID('SK_4301104032'), CONVERT(VARCHAR(MAX), @LUONG))

    INSERT INTO dbo.[NHANVIEN] ([MANV], [HOTEN], [EMAIL], [LUONG], [TENDN], [MATKHAU])
    VALUES (@MANV, @HOTEN, @EMAIL, @LUONG_ENCRYPTION, @TENDN, @MATKHAU_ENCRYPTION)

    CLOSE SYMMETRIC KEY [SK_4301104032];
END 
GO 

EXEC dbo.[SP_INS_NHANVIEN]	@MANV = 'NV01',
							@HOTEN = N'Nguyen Van A',
							@EMAIL = 'NVA@',
							@LUONG = '3000000',
							@TENDN = N'NVA',
							@MATKHAU = 'abcd12'
GO 


--iii)******************************************************
CREATE PROCEDURE [SP_SEL_NHANVIEN]
AS
BEGIN
	OPEN SYMMETRIC KEY [SK_4301104032] DECRYPTION BY PASSWORD = 'K4301104032'	

	SELECT [MANV], [HOTEN], [EMAIL], CONVERT(VARCHAR(MAX), DECRYPTBYKEY([LUONG])) AS [LUONGCB] 
	FROM dbo.[NHANVIEN]

	CLOSE SYMMETRIC KEY [SK_4301104032];
END
GO 

EXEC dbo.[SP_SEL_NHANVIEN]
GO