//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _BMCSDL__Lab04_CaNhan__d_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLySinhVienDonGianEntities : DbContext
    {
        public QuanLySinhVienDonGianEntities()
            : base("name=QuanLySinhVienDonGianEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Nullable<int>> SP_SEL_USER(string tENDN, string mD5PWD, string sHA1PWD)
        {
            var tENDNParameter = tENDN != null ?
                new ObjectParameter("TENDN", tENDN) :
                new ObjectParameter("TENDN", typeof(string));
    
            var mD5PWDParameter = mD5PWD != null ?
                new ObjectParameter("MD5PWD", mD5PWD) :
                new ObjectParameter("MD5PWD", typeof(string));
    
            var sHA1PWDParameter = sHA1PWD != null ?
                new ObjectParameter("SHA1PWD", sHA1PWD) :
                new ObjectParameter("SHA1PWD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_SEL_USER", tENDNParameter, mD5PWDParameter, sHA1PWDParameter);
        }
    
        public virtual ObjectResult<SP_SEL_ENCRYPT_NHANVIEN_Result> SP_SEL_ENCRYPT_NHANVIEN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEL_ENCRYPT_NHANVIEN_Result>("SP_SEL_ENCRYPT_NHANVIEN");
        }
    }
}
