/*--------------------------------------------
LAB: 03 - 280
NGÀY: 27/05/2020
HỌ TÊN CÁC THÀNH VIÊN NHÓM:
1. Võ Thế Duy - 43.01.104.032
2. Nguyễn Minh Pháp - 43.01.104.124
3. Châu Bảo Thịnh - 43.01.104.169
4. Nguyễn Doãn Tứ - 43.01.104.196
5. Trần Minh Trường - 43.01.104.201
--------------------------------------------*/

CREATE DATABASE QLSVNhom
GO

USE QLSVNhom
GO

CREATE TABLE SINHVIEN
(
	MASV VARCHAR(20) CONSTRAINT PK_SINHVIEN_MASV PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL
)
GO

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(20) CONSTRAINT PK_NHANVIEN_MANV PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(MAX),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL,
	PUBKEY VARCHAR(20)
)
GO

CREATE TABLE LOP
(
	MALOP VARCHAR(20) CONSTRAINT PK_LOP_MALOP PRIMARY KEY,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20)
)
GO

CREATE TABLE HOCPHAN
(
	MAHP VARCHAR(20) CONSTRAINT PK_HOCPHAN_MAHP PRIMARY KEY,
	TENHP NVARCHAR(100) NOT NULL,
	SOTC INT 
)
GO

CREATE TABLE BANGDIEM
(
	MASV VARCHAR(20),
	MAHP VARCHAR(20),
	DIEMTHI VARBINARY(MAX),
	CONSTRAINT PK_BANGDIEM PRIMARY KEY (MASV, MAHP)
)
GO

ALTER TABLE BANGDIEM ADD CONSTRAINT FK_BANGDIEM_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN (MASV)
ALTER TABLE BANGDIEM ADD CONSTRAINT FK_BANGDIEM_HOCPHAN FOREIGN KEY (MAHP) REFERENCES HOCPHAN (MAHP)
ALTER TABLE LOP ADD CONSTRAINT FK_LOP_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)
ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY (MALOP) REFERENCES LOP (MALOP)
GO

--i

CREATE PROC SP_INS_PUBLIC_NHANVIEN 
@MaNV VARCHAR(20), @HoTEN NVARCHAR(100), @EmAIL VARCHAR(20), @LuONGCB INT, @TeNDN NVARCHAR(100), @MaTKHAU VARCHAR(32)
AS 
BEGIN
	DECLARE @m VARBINARY(MAX)
	SELECT @m = HASHBYTES('SHA1',@MaTKHAU)
		DECLARE @s VARCHAR(MAX)
		SET @s = 'CREATE ASYMMETRIC KEY '+@MaNV +N'
		WITH ALGORITHM = RSA_512
		ENCRYPTION BY PASSWORD = '''+ @MaTKHAU +N''';'
		EXEC(@s)
		INSERT INTO dbo.NHANVIEN
		        ( MANV ,
		          HOTEN ,
		          EMAIL ,
		          LUONG ,
		          TENDN ,
		          MATKHAU ,
		          PUBKEY
		        )
		VALUES  ( @MaNV , -- MANV - varchar(20)
		          @HoTEN , -- HOTEN - nvarchar(100)
		          @EmAIL , -- EMAIL - varchar(20)
		          (SELECT ENCRYPTBYASYMKEY(ASYMKEY_ID(''+ @MaNV +''), CONVERT(VARCHAR(32),@LuONGCB))) , -- LUONG - varbinary(max)
		          @TeNDN , -- TENDN - nvarchar(100)
		          @m , -- MATKHAU - varbinary(max)
		          @MaNV  -- PUBKEY - varchar(20)
		        )
END
GO

--EXEC SP_INS_PUBLIC_NHANVIEN 'NV01', 'NGUYEN VAN A', 'NVA@',
--3000000, 'NVA', 'abcd12'
--SELECT * FROM dbo.NHANVIEN
--GO
--DELETE FROM dbo.NHANVIEN
--SELECT * FROM dbo.NHANVIEN
--GO
--DROP ASYMMETRIC KEY NV01

--ii
-- Chỗ này đề có vấn đề, đề cho tham số của stored là TENDN và MK, nhưng ví dụ lại dùng MANV và MK, nên nhóm em làm theo đề là sử dụng tham số TENDN ạ.
CREATE PROC SP_SEL_PUBLIC_NHANVIEN
@TeNDN NVARCHAR(100), @MK VARCHAR(32)
AS
BEGIN
	DECLARE @m VARBINARY(MAX)
	SELECT @m = HASHBYTES('SHA1',@MK)
	SELECT MANV, HOTEN, EMAIL, 
	(SELECT (CONVERT(VARCHAR(32), 
	DECRYPTBYASYMKEY(ASYMKEY_ID(''+(SELECT PUBKEY FROM dbo.NHANVIEN WHERE TENDN = @TeNDN)+''),LUONG,N''+@MK+'')))) AS LUONG FROM dbo.NHANVIEN WHERE @TeNDN = TENDN AND @m = MATKHAU
END
GO
--EXEC SP_SEL_PUBLIC_NHANVIEN 'NVA', 'abcd12'
--GO